spring.application.name=projet

# ===== AUTH DATABASE =====
spring.datasource.auth.jdbc-url=jdbc:mysql://localhost:3306/auth_microservice?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.auth.username=root
spring.datasource.auth.password=
spring.datasource.auth.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== FORMATION DATABASE =====
spring.datasource.formation.jdbc-url=jdbc:mysql://localhost:3306/formation_microservice?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.formation.username=root
spring.datasource.formation.password=
spring.datasource.formation.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA =====
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ===== SERVER =====
server.port=8081

# ===== JWT =====
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000